"""create all the tables

Revision ID: 7834c0415a51
Revises: 
Create Date: 2025-04-12 16:57:16.955118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7834c0415a51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('author_name', sa.String(length=255), nullable=False),
        sa.Column('author_bio', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    
    op.create_table('category',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('category_name', sa.String(length=120), nullable=False),
        sa.Column('category_desc', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    
    op.create_table('user',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=70), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('google_id', sa.String(length=255), nullable=True),  # New column for Google ID
        sa.Column('admin', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('google_id')  # Ensure Google ID is unique if used
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    
    op.create_table('book',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('category_id', sa.BIGINT(), nullable=False),
        sa.Column('author_id', sa.BIGINT(), nullable=False),
        sa.Column('book_title', sa.String(length=255), nullable=False),
        sa.Column('book_summary', sa.Text(), nullable=True),
        sa.Column('book_price', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('book_cover_photo', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['author.id']),
        sa.ForeignKeyConstraint(['category_id'], ['category.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    
    op.create_table('order',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('order_date', sa.TIMESTAMP(), nullable=False),
        sa.Column('order_amount', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    
    op.create_table('discount',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('book_id', sa.BIGINT(), nullable=False),
        sa.Column('discount_start_date', sa.Date(), nullable=False),
        sa.Column('discount_end_date', sa.Date(), nullable=False),
        sa.Column('discount_price', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['book.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    
    op.create_table('order_item',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('order_id', sa.BIGINT(), nullable=False),
        sa.Column('book_id', sa.BIGINT(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['book.id']),
        sa.ForeignKeyConstraint(['order_id'], ['order.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    
    op.create_table('review',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('book_id', sa.BIGINT(), nullable=False),
        sa.Column('review_title', sa.String(length=120), nullable=False),
        sa.Column('review_details', sa.Text(), nullable=True),
        sa.Column('review_date', sa.TIMESTAMP(), nullable=False),
        sa.Column('rating_start', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['book_id'], ['book.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###